package h2l.se.uit.placesaroundme;

/**
 * Created by Luantm on 11/8/2016.
 */

public class PlaceCD {
    public static String[] place_cd = new String[]{


            "accounting",
            "airport",
            "amusement_park",
            "aquarium",
            "art_gallery",
            "atm",
            "bakery",
            "bank",
            "bar",
            "beauty_salon",
            "bicycle_store",
            "book_store",
            "bowling_alley",
            "bus_station",
            "cafe",
            "campground",
            "car_dealer",
            "car_rental",
            "car_repair",
            "car_wash",
            "casino",
            "cemetery",
            "church",
            "city_hall",
            "clothing_store",
            "convenience_store",
            "courthouse",
            "dentist",
            "department_store",
            "doctor",
            "electrician",
            "electronics_store",
            "embassy",
            "fire_station",
            "florist",
            "funeral_home",
            "furniture_store",
            "gas_station",


            "gym",
            "hair_care",
            "hardware_store",
            "hindu_temple",
            "home_goods_store",

            "hospital",
            "insurance_agency",
            "jewelry_store",
            "laundry",
            "lawyer",
            "library",
            "liquor_store",
            "local_government_office",
            "locksmith",
            "lodging",
            "meal_delivery",
            "meal_takeaway",
            "mosque",
            "movie_rental",
            "movie_theater",
            "moving_company",
            "museum",
            "night_club",
            "painter",
            "park",
            "parking",
            "pet_store",
            "pharmacy",
            "physiotherapist",
            "plumber",
            "police",
            "post_office",
            "real_estate_agency",
            "restaurant",
            "roofing_contractor",
            "rv_park",
            "school",
            "shoe_store",
            "shopping_mall",
            "spa",
            "stadium",
            "storage",
            "store",
            "subway_station",
            "synagogue",
            "taxi_stand",
            "train_station",
            "transit_station",
            "travel_agency",
            "university",
            "veterinary_care",
            "zoo"
    };

    public static String[] places = new String[]{



            "Accounting",
            "Airport",
            "Amusement park",
            "Aquarium",
            "Art gallery",
            "Atm",
            "Bakery",
            "Bank",
            "Bar",
            "Beauty salon",
            "Bicycle store",
            "Book store",
            "Bowling alley",
            "Bus station",
            "Cafe",
            "Campground",
            "Car dealer",
            "Car rental",
            "Car repair",
            "Car wash",
            "Casino",
            "Cemetery",
            "Church",
            "City hall",
            "Clothing store",
            "Convenience store",
            "Courthouse",
            "Dentist",
            "Department store",
            "Doctor",
            "Electrician",
            "Electronics store",
            "Embassy",
            "Fire station",
            "Florist",
            "Funeral home",
            "Furniture store",
            "Gas station",


            "Gym",
            "Hair care",
            "Hardware store",
            "Hindu temple",
            "Home goods store",

            "Hospital",
            "Insurance agency",
            "Jewelry store",
            "Laundry",
            "Lawyer",
            "Library",
            "Liquor store",
            "Local government office",
            "Locksmith",
            "Lodging",
            "Meal delivery",
            "Meal takeaway",
            "Mosque",
            "Movie rental",
            "Movie theater",
            "Moving company",
            "Museum",
            "Night club",
            "Painter",
            "Park",
            "Parking",
            "Pet store",
            "Pharmacy",
            "Physiotherapist",
            "Plumber",
            "Police",
            "Post office",
            "Real estate agency",
            "Restaurant",
            "Roofing contractor",
            "Rv park",
            "School",
            "Shoe store",
            "Shopping mall",
            "Spa",
            "Stadium",
            "Storage",
            "Store",
            "Subway station",
            "Synagogue",
            "Taxi stand",
            "Train station",
            "Transit station",
            "Travel agency",
            "university",
            "veterinary care",
            "Zoo"


    };
}
